services:
  database:
    image: postgres:14
    container_name: database
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./postgres/postgres.env
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    ports:
      - 8080:80
    env_file:
      - ./pgadmin/pgadmin.env
    volumes:
      - pgadmindata:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json
      - ./pgadmin/pgpass:/pgpass
    depends_on:
      - database
volumes:
  pgdata:
  pgadmindata:
