@Restaurants.API_HostAddress = https://localhost:7285

GET {{Restaurants.API_HostAddress}}/api/restaurants

###

# Retrieve a restaurant that exists
GET {{Restaurants.API_HostAddress}}/api/restaurants/1

###

# Retrieve a restaurant that does not exist
GET {{Restaurants.API_HostAddress}}/api/restaurants/999
